//This file is autogenerated by convert-kuhn-tests.pl and the Makefile
//will overwrite and delete it!

v.clear();
v.push_back(0x00); 
tests.push_back(OneTest("Kuhn 2.1.1", v));

v.clear();
v.push_back(0xC2); v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 2.1.2", v));

v.clear();
v.push_back(0xE0); v.push_back(0xA0); v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 2.1.3", v));

v.clear();
v.push_back(0xF0); v.push_back(0x90); v.push_back(0x80); v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 2.1.4", v));

v.clear();
v.push_back(0xF8); v.push_back(0x88); v.push_back(0x80); v.push_back(0x80); v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 2.1.5", v));

v.clear();
v.push_back(0xFC); v.push_back(0x84); v.push_back(0x80); v.push_back(0x80); v.push_back(0x80); v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 2.1.6", v));

v.clear();
v.push_back(0x7F); 
tests.push_back(OneTest("Kuhn 2.2.1", v));

v.clear();
v.push_back(0xDF); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 2.2.2", v));

v.clear();
v.push_back(0xEF); v.push_back(0xBF); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 2.2.3", v));

v.clear();
v.push_back(0xF7); v.push_back(0xBF); v.push_back(0xBF); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 2.2.4", v));

v.clear();
v.push_back(0xFB); v.push_back(0xBF); v.push_back(0xBF); v.push_back(0xBF); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 2.2.5", v));

v.clear();
v.push_back(0xFD); v.push_back(0xBF); v.push_back(0xBF); v.push_back(0xBF); v.push_back(0xBF); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 2.2.6", v));

v.clear();
v.push_back(0xED); v.push_back(0x9F); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 2.3.1", v));

v.clear();
v.push_back(0xEE); v.push_back(0x80); v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 2.3.2", v));

v.clear();
v.push_back(0xEF); v.push_back(0xBF); v.push_back(0xBD); 
tests.push_back(OneTest("Kuhn 2.3.3", v));

v.clear();
v.push_back(0xF4); v.push_back(0x8F); v.push_back(0xBF); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 2.3.4", v));

v.clear();
v.push_back(0xF4); v.push_back(0x90); v.push_back(0x80); v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 2.3.5", v));

v.clear();
v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 3.1.1", v));

v.clear();
v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 3.1.2", v));

v.clear();
v.push_back(0x80); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 3.1.3", v));

v.clear();
v.push_back(0x80); v.push_back(0xBF); v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 3.1.4", v));

v.clear();
v.push_back(0x80); v.push_back(0xBF); v.push_back(0x80); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 3.1.5", v));

v.clear();
v.push_back(0x80); v.push_back(0xBF); v.push_back(0x80); v.push_back(0xBF); v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 3.1.6", v));

v.clear();
v.push_back(0x80); v.push_back(0xBF); v.push_back(0x80); v.push_back(0xBF); v.push_back(0x80); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 3.1.7", v));

v.clear();
v.push_back(0x80); v.push_back(0xBF); v.push_back(0x80); v.push_back(0xBF); v.push_back(0x80); v.push_back(0xBF); v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 3.1.8", v));

v.clear();
v.push_back(0xC0); 
tests.push_back(OneTest("Kuhn 3.3.1", v));

v.clear();
v.push_back(0xE0); v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 3.3.2", v));

v.clear();
v.push_back(0xF0); v.push_back(0x80); v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 3.3.3", v));

v.clear();
v.push_back(0xF8); v.push_back(0x80); v.push_back(0x80); v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 3.3.4", v));

v.clear();
v.push_back(0xFC); v.push_back(0x80); v.push_back(0x80); v.push_back(0x80); v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 3.3.5", v));

v.clear();
v.push_back(0xDF); 
tests.push_back(OneTest("Kuhn 3.3.6", v));

v.clear();
v.push_back(0xEF); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 3.3.7", v));

v.clear();
v.push_back(0xF7); v.push_back(0xBF); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 3.3.8", v));

v.clear();
v.push_back(0xFB); v.push_back(0xBF); v.push_back(0xBF); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 3.3.9", v));

v.clear();
v.push_back(0xFD); v.push_back(0xBF); v.push_back(0xBF); v.push_back(0xBF); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 3.3.10", v));

v.clear();
v.push_back(0xC0); v.push_back(0xE0); v.push_back(0x80); v.push_back(0xF0); v.push_back(0x80); v.push_back(0x80); v.push_back(0xF8); v.push_back(0x80); v.push_back(0x80); v.push_back(0x80); v.push_back(0xFC); v.push_back(0x80); v.push_back(0x80); v.push_back(0x80); v.push_back(0x80); v.push_back(0xDF); v.push_back(0xEF); v.push_back(0xBF); v.push_back(0xF7); v.push_back(0xBF); v.push_back(0xBF); v.push_back(0xFB); v.push_back(0xBF); v.push_back(0xBF); v.push_back(0xBF); v.push_back(0xFD); v.push_back(0xBF); v.push_back(0xBF); v.push_back(0xBF); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 3.3.10", v));

v.clear();
v.push_back(0xFE); 
tests.push_back(OneTest("Kuhn 3.5.1", v));

v.clear();
v.push_back(0xFF); 
tests.push_back(OneTest("Kuhn 3.5.2", v));

v.clear();
v.push_back(0xFE); v.push_back(0xFE); v.push_back(0xFF); v.push_back(0xFF); 
tests.push_back(OneTest("Kuhn 3.5.3", v));

v.clear();
v.push_back(0x2F); 
tests.push_back(OneTest("Kuhn 3.5.3", v));

v.clear();
v.push_back(0xC0); v.push_back(0xAF); 
tests.push_back(OneTest("Kuhn 4.1.1", v));

v.clear();
v.push_back(0xE0); v.push_back(0x80); v.push_back(0xAF); 
tests.push_back(OneTest("Kuhn 4.1.2", v));

v.clear();
v.push_back(0xF0); v.push_back(0x80); v.push_back(0x80); v.push_back(0xAF); 
tests.push_back(OneTest("Kuhn 4.1.3", v));

v.clear();
v.push_back(0xF8); v.push_back(0x80); v.push_back(0x80); v.push_back(0x80); v.push_back(0xAF); 
tests.push_back(OneTest("Kuhn 4.1.4", v));

v.clear();
v.push_back(0xFC); v.push_back(0x80); v.push_back(0x80); v.push_back(0x80); v.push_back(0x80); v.push_back(0xAF); 
tests.push_back(OneTest("Kuhn 4.1.5", v));

v.clear();
v.push_back(0xC1); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 4.2.1", v));

v.clear();
v.push_back(0xE0); v.push_back(0x9F); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 4.2.2", v));

v.clear();
v.push_back(0xF0); v.push_back(0x8F); v.push_back(0xBF); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 4.2.3", v));

v.clear();
v.push_back(0xF8); v.push_back(0x87); v.push_back(0xBF); v.push_back(0xBF); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 4.2.4", v));

v.clear();
v.push_back(0xFC); v.push_back(0x83); v.push_back(0xBF); v.push_back(0xBF); v.push_back(0xBF); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 4.2.5", v));

v.clear();
v.push_back(0xC0); v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 4.3.1", v));

v.clear();
v.push_back(0xE0); v.push_back(0x80); v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 4.3.2", v));

v.clear();
v.push_back(0xF0); v.push_back(0x80); v.push_back(0x80); v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 4.3.3", v));

v.clear();
v.push_back(0xF8); v.push_back(0x80); v.push_back(0x80); v.push_back(0x80); v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 4.3.4", v));

v.clear();
v.push_back(0xFC); v.push_back(0x80); v.push_back(0x80); v.push_back(0x80); v.push_back(0x80); v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 4.3.5", v));

v.clear();
v.push_back(0xED); v.push_back(0xA0); v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 5.1.1", v));

v.clear();
v.push_back(0xED); v.push_back(0xAD); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 5.1.2", v));

v.clear();
v.push_back(0xED); v.push_back(0xAE); v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 5.1.3", v));

v.clear();
v.push_back(0xED); v.push_back(0xAF); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 5.1.4", v));

v.clear();
v.push_back(0xED); v.push_back(0xB0); v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 5.1.5", v));

v.clear();
v.push_back(0xED); v.push_back(0xBE); v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 5.1.6", v));

v.clear();
v.push_back(0xED); v.push_back(0xBF); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 5.1.7", v));

v.clear();
v.push_back(0xED); v.push_back(0xA0); v.push_back(0x80); v.push_back(0xED); v.push_back(0xB0); v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 5.2.1", v));

v.clear();
v.push_back(0xED); v.push_back(0xA0); v.push_back(0x80); v.push_back(0xED); v.push_back(0xBF); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 5.2.2", v));

v.clear();
v.push_back(0xED); v.push_back(0xAD); v.push_back(0xBF); v.push_back(0xED); v.push_back(0xB0); v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 5.2.3", v));

v.clear();
v.push_back(0xED); v.push_back(0xAD); v.push_back(0xBF); v.push_back(0xED); v.push_back(0xBF); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 5.2.4", v));

v.clear();
v.push_back(0xED); v.push_back(0xAE); v.push_back(0x80); v.push_back(0xED); v.push_back(0xB0); v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 5.2.5", v));

v.clear();
v.push_back(0xED); v.push_back(0xAE); v.push_back(0x80); v.push_back(0xED); v.push_back(0xBF); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 5.2.6", v));

v.clear();
v.push_back(0xED); v.push_back(0xAF); v.push_back(0xBF); v.push_back(0xED); v.push_back(0xB0); v.push_back(0x80); 
tests.push_back(OneTest("Kuhn 5.2.7", v));

v.clear();
v.push_back(0xED); v.push_back(0xAF); v.push_back(0xBF); v.push_back(0xED); v.push_back(0xBF); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 5.2.8", v));

v.clear();
v.push_back(0xEF); v.push_back(0xBF); v.push_back(0xBE); 
tests.push_back(OneTest("Kuhn 5.3.1", v));

v.clear();
v.push_back(0xEF); v.push_back(0xBF); v.push_back(0xBF); 
tests.push_back(OneTest("Kuhn 5.3.2", v));

